# filename: docker-compose.yml
version: '3.8'

services:
  postgres-db1:
    image: postgres:14-alpine
    container_name: postgres-db1
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5431:5432"
    volumes:
      - db1-data:/var/lib/postgresql/data

  postgres-db2:
    image: postgres:14-alpine
    container_name: postgres-db2
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - db2-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  db1-data:
  db2-data: